In [10]:
from __future__ import print_function
import torch

In [11]:
x = torch.empty(5, 3)
print(x)

x = torch.rand(2, 2)
print(x)

y = torch.tensor([[3, 3], [3, 3]], dtype=torch.float)

y.add_(x)  # In-place operations have an underscore at the end
print(y)

tensor([[1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38],
        [1.0653e-38, 9.5510e-39, 1.0561e-38],
        [1.0194e-38, 1.1112e-38, 1.0561e-38],
        [9.9184e-39, 1.0653e-38, 4.1327e-39]])
tensor([[0.3571, 0.6803],
        [0.9107, 0.0928]])
tensor([[3.3571, 3.6803],
        [3.9107, 3.0928]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([-0.7379])
-0.7379130125045776


In [13]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings
    print(x)
    

tensor([-0.7379], device='cuda:0')
